### PR TITLE
Update vala-panel and vala-panel-appmenu base on review feedback

### PR DESCRIPTION
**Pull request by flexiondotorg**
This pull request improves the packaging for `vala-panel` and `vala-panel-appmenu` based on review feedback I have received. I've also addressed and significant issues reported by `lintian`.

### CODE REVIEW

**Comment by rilian-la-te** [comment]
1. Please commit man to runner into main repository, it is not debian specific. 
2. Why split libvalapanel? It is not coinstallable. 
3. Which version of Debian can read this?

**Comment by flexiondotorg** [comment]
I'll push a man page upstream later. libvalapanel0 is required because it is Debian policy to always split libraries. This is suitable for Ubuntu 17.10 and Debian 9.

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rilian-la-te** [comment]
About 1 and 3 - ok. About library splitting - do we have a way to not to split libraries? (AFAIK, lxpanel is not split). If there is no way, I will commit it. If way exists, I am strongly for keep library and executable in one package. Because it is unsplittable for now, and I do not maintain ABI and API compatibility.

**Comment by flexiondotorg** [comment]
It os Debian policy to always split libraries. Lintian reports a critical issue if you do not and a Debian Developer sponsoring the upload won't upload unless the library is split. 

That said I've created a direct link between the vala-panel package (containing the executables) and libvalapanel0, so they will always move in lock step. 

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flexiondotorg** [comment]
@rilian-la-te Don't merge this yet. I have been issue another long list of things I need to do to improve the packaging. More commits coming...

**Comment by rilian-la-te** [comment]
Ok then. I will wait for other. And I do not know how Jayatana works. I Just forked it and used CMake.

**Pull request merged**
